# Generated by Django 4.2 on 2025-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveIndex(
            model_name='chathistory',
            name='main_chathi_user_id_9faf86_idx',
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user_id', 'timestamp'], name='main_chathi_user_id_8dc3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id'], name='main_chathi_session_9134ba_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['problem', 'created_at'], name='main_soluti_problem_d40552_idx'),
        ),
        migrations.AddConstraint(
            model_name='chathistory',
            constraint=models.UniqueConstraint(fields=('user_id', 'session_id', 'question', 'timestamp'), name='unique_chat_interaction'),
        ),
        migrations.AlterModelTable(
            name='chathistory',
            table='main_chathistory',
        ),
    ]
