# Generated by Django 5.1.4 on 2025-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mathproblem_remove_message_conversation_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathproblem',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='conversation_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mathproblem',
            index=models.Index(fields=['question'], name='main_mathpr_questio_d847f6_idx'),
        ),
        migrations.AddIndex(
            model_name='mathproblem',
            index=models.Index(fields=['last_accessed'], name='main_mathpr_last_ac_ce972d_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['approach_type', 'problem'], name='main_soluti_approac_67244f_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['created_at'], name='main_soluti_created_eb9710_idx'),
        ),
    ]
