# Generated by Django 5.1.4 on 2025-01-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mathproblem_last_accessed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='solution',
            name='main_soluti_approac_67244f_idx',
        ),
        migrations.RemoveIndex(
            model_name='solution',
            name='main_soluti_created_eb9710_idx',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='conversation_history',
        ),
        migrations.AddField(
            model_name='solution',
            name='context_data',
            field=models.JSONField(default=dict),
        ),
    ]
